### PR TITLE
fmt.sh: Render all d2 diagrams automatically

### LINKED ISSUE #1: Add support for checking that all D2 renders are up to date
For every `.d2` file, we should check that the corresponding `.svg` exists and is up to date.

### PR DESCRIPTION
**Pull request by nhooyr**
Closes #1

### CODE REVIEW

**Comment by nhooyr** [comment]
Maybe we should have a separate `gen.sh`? This doesn't really seem like something that belongs in fmt. `go mod tidy` and `package.json` too are more gen. likewise with `mdtocsubst`

**Review by alixander — COMMENTED** [review]
where does it gen to?

**Comment by nhooyr** [comment]
> where does it gen to?

The default, just the same file name but as `.svg`

**Comment by nhooyr** [comment]
Oh noo, I should actually make this instead just `d2 fmt` for now.

**Review by alixander — APPROVED** [review]

**Pull request merged**
